name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    container:
      image: vapor/swift:5.5
    services:
      psql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checking out repo'
        uses: actions/checkout@v2
      - name: 'Running Integration Tests'
        run: swift test --enable-test-discovery --sanitize=thread
        env:
         DATABASE_PORT: 5432
         DATABASE_USERNAME: vapor_username
         DATABASE_PASSWORD: vapor_password
         DATABASE_NAME: vapor_database
         DATABASE_HOST: psql
